const data = [
  {
    id: "419FKwHtnB2To6cQHVchaR",
    name: "Hello",
    artist: "KAROL G",
    album: "DJ Súbele el volumen",
    uri: "spotify:track:419FKwHtnB2To6cQHVchaR",
  },
  {
    id: "3fefFQgDiTe1vx1boSfhFf",
    name: "Hello mama",
    artist: "TaitosmitH",
    album: "Hello mama",
    uri: "spotify:track:3fefFQgDiTe1vx1boSfhFf",
  },
  {
    id: "7snRPf9l4LRCMV3hD8WD3W",
    name: "Hello",
    artist: "SEVENTEEN",
    album: "SEVENTEEN 2ND ALBUM 'TEEN, AGE'",
    uri: "spotify:track:7snRPf9l4LRCMV3hD8WD3W",
  },
  {
    id: "3cGp1jXxLReLKz7QgVbWZR",
    name: "Hello",
    artist: "JOY",
    album: "Hello - Special Album",
    uri: "spotify:track:3cGp1jXxLReLKz7QgVbWZR",
  },
  {
    id: "332GJ8ykVuEt3jOT1sy7j6",
    name: "Hello Future",
    artist: "NCT DREAM",
    album: "Hello Future - The 1st Album Repackage",
    uri: "spotify:track:332GJ8ykVuEt3jOT1sy7j6",
  },
  {
    id: "1Yk0cQdMLx5RzzFTYwmuld",
    name: "Hello",
    artist: "Adele",
    album: "25",
    uri: "spotify:track:1Yk0cQdMLx5RzzFTYwmuld",
  },
  {
    id: "0NXcvC3vstK3uuz3fRc38I",
    name: "Hello / How Are You",
    artist: "Nanou",
    album: "Exit Tunes Presents Kamikyoku Wo Utattemita 3",
    uri: "spotify:track:0NXcvC3vstK3uuz3fRc38I",
  },
  {
    id: "1ZseaIKt19broBzze3F8hz",
    name: "Hello, Anxiety",
    artist: "Phum Viphurit",
    album: "Hello, Anxiety",
    uri: "spotify:track:1ZseaIKt19broBzze3F8hz",
  },
  {
    id: "5jjXaYQqhTk1KorxvWMBXm",
    name: "Hello",
    artist: "Official HIGE DANdism",
    album: "Editorial",
    uri: "spotify:track:5jjXaYQqhTk1KorxvWMBXm",
  },
  {
    id: "7J6M4EbW2TeFnMX6TSc4sg",
    name: "Hello",
    artist: "Pop Smoke",
    album: "Gaming Music Hip Hop",
    uri: "spotify:track:7J6M4EbW2TeFnMX6TSc4sg",
  },
  {
    id: "3THdOskGxdJcRbp0DcS4s0",
    name: "Life Is Still Going On",
    artist: "NCT DREAM",
    album: "Hello Future - The 1st Album Repackage",
    uri: "spotify:track:3THdOskGxdJcRbp0DcS4s0",
  },
  {
    id: "5M13MqCBVJykhVUXgjjYcX",
    name: "Hello/Hello",
    artist: "MAISONdes",
    album: "Hello/Hello",
    uri: "spotify:track:5M13MqCBVJykhVUXgjjYcX",
  },
  {
    id: "1PZCEDvDL7BvZ6RxJ6YHxR",
    name: "Hello",
    artist: "MAMAMOO",
    album: "Hello",
    uri: "spotify:track:1PZCEDvDL7BvZ6RxJ6YHxR",
  },
  {
    id: "72ysGFB4mZTgQsPqN9PzPS",
    name: "Hello Bitches",
    artist: "CL",
    album: "Hello Bitches",
    uri: "spotify:track:72ysGFB4mZTgQsPqN9PzPS",
  },
  {
    id: "7ns2KiFCA3Yatvi1jLHcB2",
    name: "여보세요 Hello",
    artist: "GOT7",
    album: "Got It?",
    uri: "spotify:track:7ns2KiFCA3Yatvi1jLHcB2",
  },
  {
    id: "0jEvTzBPDiqJbRUyqeMOLW",
    name: "Hello Mama",
    artist: "TaitosmitH",
    album: "ไททศมิตร",
    uri: "spotify:track:0jEvTzBPDiqJbRUyqeMOLW",
  },
  {
    id: "1PJKz7hjC7wQcvIfWffiJl",
    name: "Hello!",
    artist: "Super Simple Songs",
    album: "The Bath Song & More Kids Songs",
    uri: "spotify:track:1PJKz7hjC7wQcvIfWffiJl",
  },
  {
    id: "1RMfW7slHupdrvGL2MhWoU",
    name: "Hello Friday",
    artist: "Flo Rida",
    album: "Best Rap Cutz of 2016",
    uri: "spotify:track:1RMfW7slHupdrvGL2MhWoU",
  },
  {
    id: "3zQyl7ko8alM35mvYWmHuu",
    name: "Hello, Sunset",
    artist: "Red Velvet",
    album: "Queendom - The 6th Mini Album",
    uri: "spotify:track:3zQyl7ko8alM35mvYWmHuu",
  },
  {
    id: "5aaQ3Zl5rloIZ5TSWd0fVk",
    name: "Hello",
    artist: "Official HIGE DANdism",
    album: "Hello",
    uri: "spotify:track:5aaQ3Zl5rloIZ5TSWd0fVk",
  },
];

export default data;
